#### Config for CB-Spider PoC ####

## Config for OpenStack ##
openstack:

  # OpenStack Credential Info
  # domain_name: {domain_name}
  # identity_endpoint: http://{ip}/identity/v3   # for devstak-queens
  identity_endpoint: http://182.252.135.60:5000/v3
  project_id: 048be383b3a34780bf6a750ca7e9fbc8
  domain_name: default
  username: etri
  password: erti123!
  region: RegionOne
  #identity_endpoint: http://{ip}:5000/v3
  #password: {password}
  #project_id: {project_id}
  #username: {username}
  #region: {region}

  # OpenStack VM Deployment Info
#  vm_name: {vm_name}
#  image_id: {image_id}
#  flavor_id: {flavor_id}
#  network_id: {network_id}
#  security_groups: {security_groups}
#  keypair_name: {keypair_name}

  # OpenStack Test VM Info
#  server_id: {server_id}

  image_info:
    name: mcb_custom_image.iso

  keypair_info:
    name: mcb-test-key

  security_group_info:
    name: mcb-test-security

  vnet_info:
    name: mcb-test-vnet

  subnet_info:
#    id: {subnet_id}

  router_info:
    name: mcb-router
 #   gateway_id: {gateway_id}
    adminstatup: true

## Config for AZURE ##
azure:

  # Azure Credential Info
  client_id: 2993f4cd-0f4f-44c3-90af-5964e807b7e0
  client_secret: "]V=DVEneHrl@x0d]mZ9WfftAjhB225G@"
  tenant_id: adeb9c43-7b4c-4abf-a58f-221c7d32e7b3
  subscription_id: cb592624-b77b-4a8f-bb13-0e5a48cae40f

  # Azure VM Deployment Info
  location: koreacentral
  vm_size: Standard_B1ls
  image:
    publisher: Canonical
    offer: UbuntuServer
    sku: 16.04.0-LTS
    version: latest
    compute_name: mcb-test-vm

  admin_username: cloudit
  admin_password: qwe1212!Q

  nic:
    id: /subscriptions/cb592624-b77b-4a8f-bb13-0e5a48cae40f/resourceGroups/inno-platform1-rsrc-grup/providers/Microsoft.Network/networkInterfaces/Test-mcb-test-vnic

  # Azure Test VM Info
  group_name: CB-GROUP
  vm_name: mcb-test-vm

  image_info:
    group_name: inno-platform1-rsrc-grup
    name: mcb-test-image

  public_ip:
    group_name: inno-platform1-rsrc-grup
    name: mcb-test-publicip

  security_group:
    group_name: inno-platform1-rsrc-grup
    name: mcb-test-sg

  virtual_network:
    group_name: inno-platform1-rsrc-grup
    name: mcb-test-vnet

  network_interface:
    group_name: inno-platform1-rsrc-grup
    name: mcb-test-vnic




aws:

  # AWS Credential Info
  aws_access_key_id: None
  aws_secret_access_key: None
  region: ap-northeast-2

  # AMI
  image_id: ami-047f7b46bd6dd5d84

  # EC2
  ec2_instance_id: i-04f1693f5e94c1c79
  base_name: mcloud-barista
  instance_type: t2.micro
  #  key_name: mcloud-barista-keypair
  key_name: powerkimkeypair
  min_count: 1
  max_count: 1

  # Network
  subnet_id: subnet-c3b446ab
  security_group_id: sg-07ec42983dbc5e36e


## Config for Cloudit ##
cloudit:

  # Cloudit Credential Info
  user_id: cloudit
  password: cloudit
  #  identity_endpoint: http://stg.cloudit.co.kr:9090
  identity_endpoint: http://182.252.135.31:9090
  #  auth_token: ddd8e54a5bac82eea3de7c347ff8a253d0dc563d
  auth_token: 05ae4abeebf06cc29a1d5c96c5fc4459abf7ee1d
  #  tenant_id: tnt0008
  tenant_id: tnt0009
  server_id: 7b35148e-b033-4749-a29e-12beddaebbfa

  # Cloudit VM Create Info
  vm_info:
    template_id: a846af3b-5d80-4182-b38e-5501ad9f78f4
    spec_id: 1c38e438-ede9-4df5-8775-2ce791698924
    name: mcb-vm
    root_password: xxx
    subnet_addr: 10.0.8.0
    sec_groups: b2be62e7-fd29-43ff-b008-08ae736e092a
    description: mcb-test-vm
    protection: 0

  # Cloudit Resource Create Info
  resource:
    image:
      name: mcb-test-img
    public_ip:
      name: mcb-test-pubip
    security_group:
      name: mcb-test-sg
    vnet_info:
      name: mcb-test-vnet
    vnic_info:
      vm_id: 025e5edc-54ad-4b98-9292-6eeca4c36a6d
      mac: AC:DE:48:00:08:05
    vm_info:
      name: mcb-test-vm
